### ISSUE TITLE
Testing repo

### ISSUE THREAD

**Issue by alaamohamed2** [kochlisGit/autonomous-vehicles-agent#2]

**Comment by alaamohamed2** [comment]
> Thanks a lot for your help , I have few questions,
> What folders should appear after training, I got a checkpoint folder but I didn’t have any .png files or another folder ,for how long should I train your model?
> How I know that specific vehicle that I test model on as there are a lot of vehicles, how can I distinguish this trained car?
> After an episode in the training I got that average return is zero ,what does this mean?
> When I test I always got this
> ![36B2E97E-2D30-4EEC-8D04-6B9094BC5763](https://user-images.githubusercontent.com/48522202/118075214-d8083f80-b3af-11eb-8ddd-5b5a95ecf943.jpeg)
> What does this mean and also how can I know car to be able to see its behavior in testing
> I got a folder called validation_log4 full of .png files but of same location after testing ,meanwhile in testing car doesn’t move , how can car move in testing
> 
> Can you please help me
> 
> thanks in advance

**Comment by kochlisGit** [comment]
The vehicle shoud move by itself. Apparently, the vehicle is not trained and all it does is stand still and receive negative rewards.
